sim_config:
  nsky_sim: 50
  ndet_sim: 50
  save_summary: True
  save_sim: True
  config_dir: config

universe:
  dust:
    spectral_index: 1.5
    amplitude: 1.2E-2
    scale_frequency: 353.0
    scale_temperature: { var_type : pdf, fname : Pdf/dustTemperature.txt }
  synchrotron:
    spectral_index: -3.0
    amplitude: 2.0E-4
    scale_frequency: 30.
  atmosphere:
    atm_model_file: atm_20201217.hdf5

instrument:
  site : Atacama
  sky_temp : None
  elevation : 50.
  pwv : { var_type : pdf, fname : Pdf/pwv.txt }
  obs_time : 5.
  sky_fraction : 0.2
  obs_effic :  { var_type : pdf, fname : Pdf/observationEfficiency.txt }
  NET : 1.0  
  readout:
    read_noise_frac: .1
    dwell_time: None
    revisit_rate: None  
  optics_config:
    default:
      temperature: 273.
      reflection: 0.
      scatter_frac: 0.
      spillover: 0.
    elements:
      primary: { obj_type : Mirror, temperature : 273., absorption : 0.002, spillover : 0.01 }
      mirror: { obj_type : Mirror, temperature : 273., absorption : 0.002 }
      window:
        temperature : { var_type : pdf, fname : Pdf/Window_temperature.txt }
        absorption : 0.005
        reflection : { var_type : dist, fname : Bands/Optics/Window_reflection.txt }
        spillover : 0.02
        scatter_frac : { var_type : dist, fname : Bands/Optics/Window_scatterFrac.txt }
      IRshader1: { temperature : 291, absorption : 0.001 }
      IRshader2: { temperature : 245., absorption : 0.001 }
      IRshader3: { temperature : 200., absorption : 0.001 }
      abs_filter: { temperature : 90., absorption : 0.01, reflection : 0.02 }
      low_pass1: { temperature : 40., absorption : 0.01, reflection : 0.05 }
      lens1: { temperature : 4., absorption : 0.01, reflection : 0.005 }
      low_pass2: { temperature : 4., absorption : 0.01, reflection : 0.05 }
      lens2: { temperature : 2., absorption : 0.005, reflection : 0.005 }
      aperture: { obj_type : ApertureStop, absorption: 0., temperature : 2. }
      low_pass3: { temperature : 2., absorption : 0.01, reflection : 0.05 }
      lens3: { temperature : 2., absorption : 0.005, reflection : 0.005 }
      low_pass4: { temperature : 1.5, absorption : 0.01, reflection : 0.05 }
  channel_default:
    band_center: 100.
    fractional_bandwidth: .35    
    band_response: 1.
    pixel_size: 6.8
    num_det_per_water: 542
    num_wafer_per_optics_tube: 1
    num_optics_tube: 3
    waist_factor: 3
    det_eff: 1.
    psat: None
    psat_factor: 3.
    carrier_index: 3
    Tc: .165
    Tc_fraction: None
    G: None
    Flink: None
    Yield: .7
    response_factor: 1.
    bolo_resistance: None
    squid_nei: None
    read_frac: None
    nyquist_inductance: None          
  camera_config:
    default:
      boresite_elevation: 0
      optical_coupling: 1
      f_number: 2.5
      bath_temperature: .1
    elements:
      cam_1:
        skip_optical_elements: [] 
        chan_config:
          elements:
            chan_1:
              band_center: 100.
              det_eff: { var_type : pdf, fname : Pdf/detEff_1.txt }
              band_response : { var_type : dist, fname : Bands/Cam_1.txt }
              read_frac: 0.1              
            chan_2:
              band_center: 150.
              fractional_bandwidth: .35    
              response_factor: 1.41
              det_eff: { var_type : pdf, fname : Pdf/detEff_2.txt }              
              squid_nei: { var_type : pdf, fname : Pdf/squidNEI_2.txt }
              bolo_resistance: { var_type: gauss, value : 1.0, errors : 0.1 }
              read_frac: None
      cam_2:
        skip_optical_elements: []
        chan_config:
          elements:
            chan_1:
              band_center: 100.
              det_eff: { var_type : pdf, fname : Pdf/detEff_1.txt }
              band_response : { var_type : dist, fname : Bands/Cam_1.txt }
              read_frac: 0.1              
            chan_2:
              band_center: 150.
              fractional_bandwidth: .35    
              response_factor: 1.41
              det_eff: { var_type : pdf, fname : Pdf/detEff_2.txt }              
              squid_nei: { var_type : pdf, fname : Pdf/squidNEI_2.txt }
              bolo_resistance: { var_type: gauss, value : 1.0, errors : 0.1 }
              read_frac: None
